### ISSUE TITLE
Internet Explorer multiple filters

### ISSUE THREAD

**Issue by f-liva** [TurbineCSS/Turbine#93] opened 2010-07-28 22:02 UTC
In Internet Explorer you can insert multiple "filter" property per CSS selector, but if i declare, in a cssp file, a box-shadow and a linear-gradient in the same selector Turbine overwrite the first with the second filter, instead of add both.

**Comment by f-liva** [comment] 2010-07-28 22:29
A precisation: this bug is present only in IE8, instead IE7 has multiple filters.

**Comment by SirPepe** [comment] 2010-07-29 14:17
The problem is that the comma between filters, which is mandatory in IE8 but not IE7, is missing. Confirmed and work in progress.

**Comment by f-liva** [comment] 2010-07-29 21:54
Very good, i wait changes ;)

**Comment by SirPepe** [comment] 2010-07-30 09:50
Fixed in 1.0.4

**Comment by f-liva** [comment] 2010-07-30 09:52
Have you already fixed? Like as speedy gonzales :P

**Closed as completed** 2010-07-30 16:50 UTC
Labels: Defect, 1.0.X, Work in progress, Mayor
